[package]
name = "task__1"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
futures = "0.3.14"
rusty-termcolor = "0.1.62"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0" }
